package com.agri.engine;

import com.agri.model.AnalysisResult;
import com.agri.model.CropData;
import com.agri.model.FarmerProfile;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Part 4 - Decision Core
 *
 * MultiStrategyGenerator produces three distinct investment plans from the
 * base AnalysisResult generated by ZaiRationaleGenerator.
 *
 * The three strategies differ in how aggressively the farmer deploys their budget:
 *   • Conservative  – 50% of budget, risk score reduced by 2, lower projected return.
 *   • Balanced      – 75% of budget, risk score unchanged from AI recommendation.
 *   • Aggressive    – 100% of budget, risk score increased by 2, highest projected return.
 *
 * Economic Impact Scaling:
 *   The GLM's economicImpact represents the projected net return for full-budget deployment.
 *   Conservative and Balanced plans scale this proportionally (×0.50 and ×0.75).
 *   This is a deliberate linear approximation; real-world diminishing returns are
 *   outside scope for this decision engine.
 *
 * Output:
 *   A LinkedHashMap<String, String> matching the strategyBreakdown field in AnalysisResult.
 *   Keys are exactly "Conservative", "Balanced", "Aggressive" (used by the UI layer).
 */
public class MultiStrategyGenerator {

    // Budget allocation fractions per strategy
    private static final double CONSERVATIVE_FRACTION = 0.50;
    private static final double BALANCED_FRACTION     = 0.75;
    private static final double AGGRESSIVE_FRACTION   = 1.00;

    // Risk score adjustments relative to the AI's base recommendation
    private static final int CONSERVATIVE_RISK_DELTA = -2;
    private static final int AGGRESSIVE_RISK_DELTA   = +2;

    /**
     * Generates the three investment strategies and returns them as a map.
     *
     * @param baseResult The parsed AnalysisResult from ZaiRationaleGenerator.
     * @param profile    The farmer's profile (budget comes from here).
     * @param marketData Current market data (used to look up the recommended crop's price).
     * @return           Map with keys "Conservative", "Balanced", "Aggressive".
     */
    public Map<String, String> generate(AnalysisResult baseResult,
                                         FarmerProfile profile,
                                         List<CropData> marketData) {

        // LinkedHashMap preserves insertion order → UI displays Conservative → Balanced → Aggressive
        Map<String, String> strategies = new LinkedHashMap<>();

        String crop        = baseResult.getRecommendedCrop();
        double budget      = profile.getBudget();
        double baseImpact  = baseResult.getEconomicImpact();
        int    baseRisk    = baseResult.getRiskScore();
        double marketPrice = findMarketPrice(crop, marketData);

        strategies.put("Conservative", buildPlan(
                "Conservative",
                crop,
                budget,
                CONSERVATIVE_FRACTION,
                baseImpact * CONSERVATIVE_FRACTION,
                clampRisk(baseRisk + CONSERVATIVE_RISK_DELTA),
                marketPrice,
                "Low-risk posture. Half the budget is deployed; remaining capital is held in "
                + "reserve as a safety buffer. Best for risk-averse farmers or first-time investors."
        ));

        strategies.put("Balanced", buildPlan(
                "Balanced",
                crop,
                budget,
                BALANCED_FRACTION,
                baseImpact * BALANCED_FRACTION,
                clampRisk(baseRisk),
                marketPrice,
                "Moderate-risk posture. 75% of budget is deployed. Balances growth opportunity "
                + "against downside risk. Aligns with the AI's core recommendation."
        ));

        strategies.put("Aggressive", buildPlan(
                "Aggressive",
                crop,
                budget,
                AGGRESSIVE_FRACTION,
                baseImpact * AGGRESSIVE_FRACTION,
                clampRisk(baseRisk + AGGRESSIVE_RISK_DELTA),
                marketPrice,
                "High-risk posture. Full budget is deployed to maximise return. Suitable only "
                + "for farmers with adequate cash reserves and high risk tolerance."
        ));

        log("INFO", "Generated 3 strategies for crop: " + crop);
        return strategies;
    }

    // ── Private helpers ──────────────────────────────────────────────────────────

    /**
     * Assembles a human-readable strategy description string.
     * Format is fixed so that the UI / AnalysisController can parse or display it consistently.
     */
    private String buildPlan(String level,
                              String crop,
                              double totalBudget,
                              double fraction,
                              double projectedImpact,
                              int    adjustedRisk,
                              double marketPricePerTon,
                              String rationale) {

        double capitalDeployed  = totalBudget * fraction;
        double capitalReserved = Math.max(0, totalBudget - capitalDeployed);

        // Estimated tonnes purchasable / producable given deployed capital
        // (marketPricePerTon is the selling price, used as a proxy for production value)
        double estimatedTonnes  = (marketPricePerTon > 0) ? capitalDeployed / marketPricePerTon : 0;

        return String.format(
                "[%s STRATEGY] "
                + "Crop: %s | "
                + "Budget Deployed: RM %.2f (%.0f%%) | "
                + "Capital Reserved: RM %.2f | "
                + "Est. Volume: %.2f tonnes | "
                + "Projected Net Return: RM %.2f | "
                + "Adjusted Risk Score: %d/10 | "
                + "Rationale: %s",

                level,
                crop,
                capitalDeployed, fraction * 100,
                capitalReserved,
                estimatedTonnes,
                projectedImpact,
                adjustedRisk,
                rationale
        );
    }

    /**
     * Searches the market data list for the recommended crop's selling price.
     * Uses getName() and getMarketPrice() – the two confirmed public getters on CropData (zip1).
     * Returns a safe default of 1.0 (not 0) to prevent divide-by-zero in volume calculation.
     */
    private double findMarketPrice(String cropName, List<CropData> marketData) {
        for (CropData crop : marketData) {
            if (crop.getName() != null && cropName != null && crop.getName().equalsIgnoreCase(cropName)) {
                return crop.getMarketPrice();
            }
        }
        log("WARN", "Market price for '" + cropName + "' not found in market data. Defaulting to 1.0.");
        return 1.0;
    }

    /**
     * Clamps a risk score to the valid 1–10 range defined by AnalysisResult.
     */
    private int clampRisk(int score) {
        return Math.max(1, Math.min(10, score));
    }

    private void log(String level, String msg) {
        System.out.println("[" + level + "][MultiStrategyGenerator] " + msg);
    }
}
